name: Continuous Integration

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "**"

  pull_request:
    branches:
      - "**:**"

  release:

  schedule:
    - cron: "0 6 * * *"

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
      - run: crystal tool format && git diff --exit-code

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: nightly
        id: crystal
      - run: for f in patches/*; do cat $f | patch -d ${{ steps.crystal.outputs.path }} -p1; done
      - run: crystal spec -Dpreview_mt spec/*_spec.cr -v
